name: brew_journal_client_bloc
description: BLoC project source for Brew Journal
version: 0.1.0
author: Seokju Na <seokju.me@gmail.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  test: ^1.0.0
